config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions
  resources :reports, only: [:index, :update]
  resources :wit_ai_uploads, :only => [:index]
  post '/wit_ai_uploads/new_upload' => 'wit_ai_uploads#create'
  get '/wit_ai_uploads/confirm_import' => 'wit_ai_uploads#confirm_import'
  get '/wit_ai_uploads/show_data' => 'wit_ai_uploads#show'
  
  root to: 'sessions#new'
end

app/models/service/report.rb
class Service::Report < ActiveApi
  attribute :id, Integer
  attribute :call_id, Integer
  attribute :message, String
  attribute :properties, Array
  attribute :location, String
  attribute :address, String
  attribute :created_at, String

  def self.endpoint_url
    '/plugin/reports/api2/reports'
  end

  def readable_report
    reports = []
    properties.each do |property|
      unless property.empty?
        report_readables = []
        report_readables.push "case:#{property[Settings.wit['case_key'].to_sym]}"
        
        if property[Settings.wit['symptoms_key'].to_sym] && property[Settings.wit['symptoms_key'].to_sym].is_a?(Array)
          symptoms = property[Settings.wit['symptoms_key'].to_sym].map { |s| s }
          report_readables.push "symptom:#{symptoms}"
        end

        reports.push report_readables.join(', ')
      end
    end
    reports.join("; ")
  end
end

app/controllers/reports_controller.rb
require 'will_paginate/array'

class ReportsController < ApplicationController
  before_action :filter_params, only: [:index]
  before_action :csv_options, only: [:index], if: :csv_request?

  def index
    begin
      @reports = Service::Report.where(@filter_params)
      @reports = @reports.paginate(page: params[:page], per_page: page_size) if html_request?
    rescue
      flash[:error] = t('report.failed_connect_verboice')
    end

    respond_to do |format|
      format.html
      format.csv
      format.xlsx { 
        response.headers['Content-Disposition'] = "attachment; filename='reports-#{Time.now}.xlsx'"
      }
    end
  end

  # PUT reports/:id
  def update
    begin
      report = Service::Report.update(params[:id], report: protected_params)
      render json: report
    rescue
      render json: '', status: 422
    end
  end

  private

  def protected_params
    params.require(:report).permit(:location, :properties => [:case, :symptom => []])
  end

  def filter_params
    @filter_params = {}
    [:from, :to, :phone_number, :location].each do |key|
      @filter_params[key] = params[key] if params[key]
    end

    page = params[:page] || 0
    @filter_params[:limit] = page_size
    @filter_params[:offset] = page_size * (page.to_i - 1)
  end

  def page_size
    Settings.default_page_size || 10
  end

  def csv_options
    @csv_options = { :force_quotes => true, :col_sep => ',' }
    @output_encoding = 'UTF-8'
    @filename = "reports-#{Time.now}.csv"
  end

  def html_request?
    request.format.html?
  end

  def csv_request?
    request.format.csv?
  end
  
end

app/views/reports/_list.html.erb
<% if @reports && @reports.size > 0 %>
  <div class='actionable pull-right'>
    <div class="btn-group pull-right">
      <a class="btn btn-primary download dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-white icon-download-alt"></i> <%= t('report.download') %> <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to reports_path(format: :csv, params: request.query_parameters.except(:page)), class: 'download' do %>
            <%= t('report.csv') %>
          <% end %>
        </li>
        <li>
          <%= link_to reports_path(format: :xlsx, params: request.query_parameters.except(:page)), class: 'download' do %>
            <%= t('report.excel') %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

<div class='report-table'>
  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th><%= t('report.date') %></th>
        <th><%= t('report.phone_number') %></th>
        <th><%= t('report.audio') %></th>
        <th><%= t('report.message') %></th>
        <th><%= t('report.symptom') %></th>
        <th><%= t('report.location') %></th>
      </tr>
    </thead>
    <tbody>
      <% if @reports && @reports.size > 0 %>
        <% @reports.each do |report| %>
          <tr>
            <td><%= show_readable_date(report["created_at"]) %></td>
            <td><%= report["address"] %></td>
            <td>
              <audio controls preload="none">
                <source src="<%= audio_path(report)%>" type="audio/x-wav">
              </audio>
            </td>
            <td><%= report["message"] %></td> 
            <td><%= text_area_tag "report_#{report['id']}_properties", report.readable_report, report_id: report['id'], class: 'editable' %>
              <span class="glyphicon glyphicon-download-alt"></span>
            </td>
            <td><%= text_area_tag "report_#{report['id']}_location", report["location"], report_id: report['id'], class: 'editable' %>
              <span class="glyphicon glyphicon-download-alt"></span>
            </td>
          </tr> 
        <% end %>  
      <% else %>
        <tr>
          <td style='color:red' colspan="6" align="center"><%= t('report.no_data') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% if @reports %>
  <%= will_paginate @reports %>
<% end %>

<script type="text/javascript">
  $(function () {
    $('#from').datepicker({format: "dd/mm/yyyy"});
    $('#to').datepicker({format: "dd/mm/yyyy"});
  });
</script>

app/views/reports/_search_form.html.erb
<div class="panel-heading">
  <h5 class="panel-title">
    <a data-toggle="collapse" href="#filter-panel">
      <i class='icon-filter'></i><%= t('report.search_criteria') %>
    </a>
  </h5>
</div>

<div id="filter-panel" class="panel-collapse collapse">
  <div class="panel-body">
    <%= form_tag reports_path(), :method => :GET do %>
      <fieldset>
        <div class="form-group">
          <div class="row">
            <div class="colspan-2">
              <label class="control-label" for="from" style="padding-right:5px;"><%= t('search.from') %></label>
              <input type="text" class="form-control" autocomplete="off"  name="from" id="from" value="<%= params[:from] %>">
            </div>
            <div class="colspan-2">
              <label class="control-label" for="to" style="padding-right:5px;"><%= t('search.to') %></label>
              <input type="text" class="form-control" autocomplete="off"  name="to" id="to" value="<%= params[:to] %>">
            </div>
            <div class="colspan-2">
              <label class="control-label" for="phone_number" style="padding-right:5px;"><%= t('search.phone_number') %></label>
            <input type="text" class="form-control" name="phone_number" id="phone_number" value="<%= params[:phone_number] %>">
            </div>
            <div class="colspan-2">
              <label class="control-label" for="location" style="padding-right:5px;"><%= t('search.location') %></label>
              <input type="text" class="form-control" name="location" id="location" value="<%= params[:location] %>">
            </div>
            <div class="colspan-2">
              <button type="subm" class="btn btn-primary" style="margin-top:25px;"><i class="icon-white icon-search"></i> <%= t('search.search') %></button>
            </div>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/reports/index.html.erb
<%= render partial: 'search_form' %>
<%= render partial: 'list', reports: @reports %>