config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions
  resources :reports, only: [:index, :update]
  resources :wit_ai_uploads, :only => [:index]
  post '/wit_ai_uploads/new_upload' => 'wit_ai_uploads#create'
  get '/wit_ai_uploads/confirm_import' => 'wit_ai_uploads#confirm_import'
  get '/wit_ai_uploads/show_data' => 'wit_ai_uploads#show'
  
  root to: 'sessions#new'
end

app/controllers/wit_ai_uploads_controller.rb
class WitAiUploadsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def confirm_import
    @file_path = Service::generate_file_path params[:file_name]
    data =  Spreadsheet.open @file_path
    for index in 0 .. (data.sheet_count - 1) do
      rows = Service::read_sheet(data,index)
      sheet_name = data.worksheet(index).name
      Service::import_entities(sheet_name, rows)
    end
    redirect_to reports_path()
  end

  def create
    @index = 0
    @file_name = Service::save_excel(params[:file])
    @file_path = Service::generate_file_path @file_name
    data =  Spreadsheet.open @file_path
    @rows = Service::read_sheet(data,@index)
    @sheet_list = []
    for index in 0 .. (data.sheet_count - 1) do
      @sheet_list << data.worksheet(index).name
    end
    render :show
  end

  def show
    @index = params[:index].to_i
    @file_name = params[:file_name]
    @file_path = Service::generate_file_path params[:file_name]
    data =  Spreadsheet.open @file_path
    @rows = Service::read_sheet(data,@index)
    @sheet_list = []
    for index in 0 .. (data.sheet_count - 1) do
      @sheet_list << data.worksheet(index).name
    end
  end

end

app/views/wit_ai_uploads/index.html.erb
<div class="ux-collapsible w40 import_csv box grey" data-on-expanded="box grey">
  <div class="ux-content">
    <h3> <%= t('import.title') %> </h3>
    <span>
      <%= t('import.desc1') %>
      <br />
      <%= t('import.desc2') %>
      <br />
      <%= t('import.desc3') %>
      <a href="template.xls"><%= t('import.here') %></a>
    </span>
    <br /><br />
    <%= form_tag(wit_ai_uploads_new_upload_path(), multipart: true, :method => 'POST') do %>
        <div class="input-group image-preview">
            <input placeholder="" type="text" id="disable-text" class="form-control image-preview-filename" disabled="disabled">
            <!-- don't give a name === doesn't send on POST/GET --> 
            <span class="input-group-btn"> 
            <!-- image-preview-clear button -->
            <button type="button" class="btn btn-default image-preview-clear" style="display:none;"> <span class="glyphicon glyphicon-remove"></span> <%= t('import.clear') %> </button>
            <!-- image-preview-input -->
            <div class="btn btn-default image-preview-input" style="margin:0px 0px 10px 0px;"> <span class="glyphicon glyphicon-folder-open"></span> <span class="image-preview-input-title"><%= t('import.browse') %></span>
              <input type="file" accept=".xls" name="file" id="file">
              <!-- rename it -->
            </div>
            <input type="submit" value="<%= t('import.submit') %>" class="btn btn-labeled btn-primary" style="margin:0px 0px 10px 0px;" id="btn-submit" disabled> <span class="btn-label"><i class="glyphicon glyphicon-upload"></i> </span></button>
            </span> 
        </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $('#file').on('change', function(e){ 
    if($('#file').get(0).files.length == 0 ){
      $("#disable-text")[0].value = "<%= t('import.no_file_selected') %>";
      $("#btn-submit")[0].disabled = true
    }
    else{
      $("#disable-text")[0].value = e.target.files[0].name; 
      $("#btn-submit")[0].disabled = false
    }
  });
</script>

app/views/wit_ai_uploads/show.html.erb
<h1>
  <%= t('import.preview_file') %>
</h1>

<div class='actionable'>
  <a href="<%= wit_ai_uploads_confirm_import_path(:file_name => @file_name)%>" class='btn btn-primary'> <%= t('import.confirm_import') %> </a>
</div>

<br />
<br />
<div class="panel with-nav-tabs panel-primary">
  <div class="panel-heading">
    <ul class="nav nav-tabs">
      <% @sheet_list.each do |list| %>
        <% if @sheet_list.find_index(list) == @index %>
          <li class="active">
            <a href="<%= wit_ai_uploads_show_data_path(:index => @sheet_list.find_index(list), :file_name => @file_name)%>" >
              <%= list %>
            </a>
          </li>
        <% else %>
          <li>
            <a href="<%= wit_ai_uploads_show_data_path(:index => @sheet_list.find_index(list), :file_name => @file_name)%>" >
              <%= list %>
            </a>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
<table class="table table-striped table-bordered">
  <% @rows.each do |r| %>
    <% if r[0] != nil and r[0] != "" %>
      <tr>
      <% for index in 0 .. (@rows.first.size - 1) do %>
        <td><%= r[index] %></td>
      <% end %>
      </tr>
    <% end %>
  <% end %>
</table>
<br/>