config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions
  resources :reports, only: [:index, :update]
  resources :wit_ai_uploads, :only => [:index]
  post '/wit_ai_uploads/new_upload' => 'wit_ai_uploads#create'
  get '/wit_ai_uploads/confirm_import' => 'wit_ai_uploads#confirm_import'
  get '/wit_ai_uploads/show_data' => 'wit_ai_uploads#show'
  
  root to: 'sessions#new'
end

app/views/layouts/_footer.html.erb
<!--
<div class="container" >
  <hr class='footer-bar' />  
  <div class="row-fluid"> 
     <div class="span6 text-left gray"> Developed by <a href='http://www.instedd.org' >InSTEDD </a> </div>
     <div class="span6 text-right gray"> Version 1.0  </div>
  </div>  
</div>

-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type='text/javascript'>
      window.app_url = "<%= Settings.url_host %>";
    </script>
  </head>

  <body>
      <div class="navbar">
      <div class="navbar-inner">
        <div class="hearder_narrow">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </a>
          <%= image_tag "logo_small.png", :alt => "<%= t('logo_title')", :width => '32',  :title => "<%= t('logo_title')", :style => "padding: 5px 10px 5px;", :class => 'brand' %>
          <a class="brand" href="/" name="top"><%= t('app_name') %></a>

          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class=<%= section_active("wit_ai_uploads")  %>><%= link_to raw("<i class='icon-download'></i> #{t('import.import_dataset')}"), wit_ai_uploads_path(), :method => :get, :style => "padding: 10px" %></li>
              <li class="divider-vertical"></li>
            </ul> 
            
            <div class="btn-group pull-right">
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="icon-user"></i> <%= current_user['email'] || t('user.unknown') %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t('login.log_out'), logout_path(), :method => :GET %></li>
              </ul>
            </div>
          </div>
        <!--/.nav-collapse -->
        </div>
      <!--/.container-fluid -->
      </div>
    <!--/.navbar-inner -->
    </div>
    <div class="body-content" style="min-width:1000px">
      <center>
        <% if flash[:error] -%>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%=h flash[:error] %>
          </div>
        <% end -%>
        <% if flash[:notice] -%>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%=h flash[:notice] %>
          </div>
        <% end -%>
      </center>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %></title>
     <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
      <!--[if lt IE 9]>
        <script src="assets/html5shiv.js"></script>
      <![endif]-->
    
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
  </head>

  <body>
    <div class="container content-body">
      <div class="row-fluid" >
        <div class="span6" style="text-align: center;">
          <div class="logo">
            <div>
            <h3><%= image_tag "logo.png", alt: t('app.name'), title: t('app.name'), :style => "padding-top: 25px;" %></h3>
            </div>
          </div>
        </div>
        <div class="span6">
          <%if alert || notice %> 
            <% css_class = alert.nil? ? "warning" : "notice"%>
            <div class="alert <%= css_class %>" >
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= alert || notice %>
            </div>
          <% end %> 
          <%= yield %>
        </div>
      </div>   
    </div>
    <footer> <%= render 'layouts/footer' %> </footer>
  </body>
</html>